robot:
  arm_id: "fr3"
  joint_relay: true
  joint_publisher: false
  robot_ip: "192.168.0.198" # Only used for joint relay. Ignore if joint relay is false.
  robot_xacro: "urdf/robot/fr3_full_skin.xacro" # Make sure the skin xacros are included in this file!
  end_effector:
    active: false
    xacro: "../end_effectors/sphere_ee.xacro" # Defined relative to the robot xacro file


controller:
  active: false
  avoidance_type: "hiro"
  movement_type: "static"

sensors:
  active: true
  publish_rate: 30.0 # Hz

  # All links defined as in xacro: i.e. '${robot.arm_id}_${link_name}' -> 'fr3_link1'
  # Launch will search for these links and activate if they are found in the xacro file.
  link1_skin: # The name of the link needs to match the name of the link in the xacro file. ex: <link name="link1"/>
    active: false
    type: "SCPS"
    SN: "S1" # Serial number of the sensor
    num_sensors: 6
    xacro: "" # Defined relative to the gentact_ros_tools_hybrid package. Leave empty to not display.
    wireless: false
    port: ''
  link2_skin:
    active: true
    type: "SCPS"
    SN: "S2" # Serial number of the sensor - will be auto-detected from ACM port
    num_sensors: 6
    xacro: "../skin/link2_fancy.xacro" # Defined relative to the gentact_ros_tools_hybrid package. Leave empty to not display.
    wireless: false
    port: ''
  link3_skin:
    active: true
    type: "SCPS"
    SN: "S3" # Serial number of the sensor - will be auto-detected from ACM port
    num_sensors: 6
    xacro: "../skin/link3_fancy.xacro" # Defined relative to the gentact_ros_tools_hybrid package. Leave empty to not display.
    wireless: false
    port: ''
  link4_skin:
    active: true
    type: "SCPS"
    SN: "S4" # Serial number of the sensor - will be auto-detected from ACM port
    num_sensors: 6
    xacro: "../skin/link4_fancy.xacro" # Defined relative to the gentact_ros_tools_hybrid package. Leave empty to not display.
    wireless: false
    port: ''
  link5_skin:
    active: true
    type: "SPAD"
    SN: "S5" # Serial number of the sensor - will be auto-detected from ACM port
    num_sensors: 3
    xacro: "../skin/link5_spad.xacro" # Defined relative to the gentact_ros_tools_hybrid package. Leave empty to not display. Defined from robot xacro file.
    wireless: false
    port: "/dev/ttyACM0" # Fallback port for SPAD sensors if auto-detection fails
  link6_skin:
    active: true
    type: "SCPS"
    SN: "S6" # Serial number of the sensor - will be auto-detected from ACM port
    num_sensors: 6
    xacro: "../skin/link6_big.xacro" # Defined relative to the gentact_ros_tools_hybrid package. Leave empty to not display. Defined from robot xacro file.
    wireless: false
    port: ''
    multiplier: [1.0,1.0,1.0,1.0,100000.0,1.0]

prediction:
  active: true
  pcl:
    active: true
    alpha: 0.003 # Sensitivity parameter.Higher -> More sensitive
    min_dist: 0.05 # Minimum distance to consider for collision avoidance. (m)
  mlp:
    active: false
    model_path: "~/self-cap-ml/saved_models/mlp_model.pth" # Absolute path to the model file. 
  mamba:
    active: false
    model_path: "~/self-cap-ml/saved_models/mamba_all.pth" # Absolute path to the model file.

visualization:
  rviz: false
  rviz_config: "/home/caleb/.rviz2/hybrid.rviz" # ignore if rviz is false
  foxglove: true

tracker:
  active: true
  baseline_timeout: 10.0 #s
  baseline_duration: 3.0 # seconds
  Kp: 0.15
  Kd: 0.001
  baseline_kp: 0.01
  baseline_ki: 0.0000001
  baseline_kd: 0.000001
  masking_threshold: 100.0 # Threshold for masking baseline updates


cameras: 
  active: false
  launch_file: "cameras.launch.py" # Launch file to launch the cameras.

calibration: # If a single skin needs to be calibrated, set active to true.
  active: false
  process: false
  xbox: false
  num_sensors: 6
  xacro: "../calibration/link5.xacro" # Defined relative to the gentact_ros_tools_hybrid package. Leave empty to not display. Defined from robot xacro file.
  wireless: false
  port: "/dev/ttyACM0" # Put publisher IP for wifi, or serial port for usb (e.g. /dev/ttyACM0).
  link_name: "calibration_sensor" # Name of the link to publish the sensor data to.
  publish_rate: 30.0 # Hz
  transform: [0, 0, 0, 0, 0, 0, 'map', 'calibration_base'] # Transform to apply to the skin.
  training_data_path: "~/self-cap-ml/data/training_data.csv" # Absolute path to the training data file.
  distance_file_path: "~/self-cap/data/data.csv" # Absolute path to the distance file.
  
